# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
orbs:
  heroku: circleci/heroku@0.0.10
workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git

jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7.4-stretch-browsers
#        environment:
#          FLASK_CONFIG: testing
#          TEST_DATABASE_URL: 'sqlite:///db/mealtime_testing.sqlite'

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout
      - run: mkdir test-reports
      - run: mkdir test-results
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!

      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m pytest test

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-reports
          destination: test-reports

      # Herokuuuuuuuuu
#      - run:
#          name: Setup Heroku
#          command: |
#            chmod +x .circleci/setup-heroku.sh
#            .circleci/setup-heroku.sh
#      - run:
#          name: Deploy to Heroku
#          command: |
#            cd app/
#            git push heroku master
